//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.17 at 04:01:02 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.wsdlexample.com/xml/student", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_wsdlexample_com.xml.student;
